<a href="https://colab.research.google.com/github/Sayak-coder/HateSpeech-detection/blob/main/hatespeech.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->nltk) (3.1.2)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import transformers
from transformers import pipeline

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/StereoQueerEval/Dataset from IIT Hydrabad/Wiki Madlibs” Eval Dataset/hi-Latn_sentence_templates.csv')
df.head()

        template  toxicity              phrase
0  i_am_identity  nontoxic        ma Purana hu
1  i_am_identity  nontoxic          ma kala hu
2  i_am_identity  nontoxic         ma andha hu
3  i_am_identity  nontoxic        ma purush hu
4  i_am_identity  nontoxic  ma Bahot Purana hu

In [ ]:
df['toxicity'].unique()

array(['nontoxic', 'toxic'], dtype=object)

In [ ]:
df = df.drop(columns='template')
df.columns

Index(['toxicity', 'phrase'], dtype='object')

In [ ]:
df.shape

(27410, 2)

In [ ]:
df['toxicity'] = df['toxicity'].map({'nontoxic': 0, 'toxic': 1})
df.head()

   toxicity              phrase
0         0        ma Purana hu
1         0          ma kala hu
2         0         ma andha hu
3         0        ma purush hu
4         0  ma Bahot Purana hu

In [ ]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [ ]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
sentences=[]
for sentence in df['phrase'] :
  sentences.append(sentence)
print(len(sentences))

27410

In [ ]:
stemmer=PorterStemmer()

In [ ]:
import re
corpus=[]
for i in range(len(sentences)):
  review = re.sub('[^a-zA-Z]',' ',sentences[i])
  review = review.lower()
  corpus.append(review)

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
for i in corpus:
  words = nltk.word_tokenize(i)
  for word in words:
    print(stemmer.stem(word))

Streaming output truncated to the last 5000 lines.
anokhi
he
bangaali
honaa
acchi
he
bangaali
honaa
pyari
he
thather
honaa
anokhi
he
thather
honaa
acchi
he
thather
honaa
pyari
he
vishamlingi
honaa
anokhi
he
vishamlingi
honaa
acchi
he
vishamlingi
honaa
pyari
he
bauddh
honaa
anokhi
he
bauddh
honaa
acchi
he
bauddh
honaa
pyari
he
bihaari
honaa
anokhi
he
bihaari
honaa
acchi
he
bihaari
honaa
pyari
he
sunni
honaa
anokhi
he
sunni
honaa
acchi
he
sunni
honaa
pyari
he
lohaar
honaa
anokhi
he
lohaar
honaa
acchi
he
lohaar
honaa
pyari
he
bhartiya
honaa
anokhi
he
bhartiya
honaa
acchi
he
bhartiya
honaa
pyari
he
maarwadi
honaa
anokhi
he
maarwadi
honaa
acchi
he
maarwadi
honaa
pyari
he
esaayi
honaa
anokhi
he
esaayi
honaa
acchi
he
esaayi
honaa
pyari
he
mexican
honaa
anokhi
he
mexican
honaa
acchi
he
mexican
honaa
pyari
he
dhobi
honaa
anokhi
he
dhobi
honaa
acchi
he
dhobi
honaa
pyari
he
muslim
honaa
anokhi
he
muslim
honaa
acchi
he
muslim
honaa
pyari
he
afriki
ameriki
honaa
anokhi
he
afriki
ameriki
honaa
acchi
he
afriki
ameriki
honaa
pyari
he
yahudi
honaa
anokhi
he
yahudi
honaa
acchi
he
yahudi
honaa
pyari
he
jaat
honaa
anokhi
he
jaat
honaa
acchi
he
jaat
honaa
pyari
he
banjaara
honaa
anokhi
he
banjaara
honaa
acchi
he
banjaara
honaa
pyari
he
samlaingik
honaa
anokhi
he
samlaingik
honaa
acchi
he
samlaingik
honaa
pyari
he
musalman
honaa
anokhi
he
musalman
honaa
acchi
he
musalman
honaa
pyari
he
afriki
honaa
anokhi
he
afriki
honaa
acchi
he
afriki
honaa
pyari
he
paakistani
honaa
anokhi
he
paakistani
honaa
acchi
he
paakistani
honaa
pyari
he
cathol
honaa
anokhi
he
cathol
honaa
acchi
he
cathol
honaa
pyari
he
paarasi
honaa
anokhi
he
paarasi
honaa
acchi
he
paarasi
honaa
pyari
he
jain
honaa
anokhi
he
jain
honaa
acchi
he
jain
honaa
pyari
he
shaanav
honaa
anokhi
he
shaanav
honaa
acchi
he
shaanav
honaa
pyari
he
samlaingik
stree
honaa
anokhi
he
samlaingik
stree
honaa
acchi
he
samlaingik
stree
honaa
pyari
he
caitholik
honaa
anokhi
he
caitholik
honaa
acchi
he
caitholik
honaa
pyari
he
japani
honaa
anokhi
he
japani
honaa
acchi
he
japani
honaa
pyari
he
sonaar
honaa
anokhi
he
sonaar
honaa
acchi
he
sonaar
honaa
pyari
he
purana
hon
pagali
ha
purana
hon
ghinoni
ha
purana
hon
kamini
ha
purana
hon
gandi
ha
kala
hon
pagali
ha
kala
hon
ghinoni
ha
kala
hon
kamini
ha
kala
hon
gandi
ha
andha
hon
pagali
ha
andha
hon
ghinoni
ha
andha
hon
kamini
ha
andha
hon
gandi
ha
purush
hon
pagali
ha
purush
hon
ghinoni
ha
purush
hon
kamini
ha
purush
hon
gandi
ha
bahot
purana
hon
pagali
ha
bahot
purana
hon
ghinoni
ha
bahot
purana
hon
kamini
ha
bahot
purana
hon
gandi
ha
kali
hon
pagali
ha
kali
hon
ghinoni
ha
kali
hon
kamini
ha
kali
hon
gandi
ha
andhi
hon
pagali
ha
andhi
hon
ghinoni
ha
andhi
hon
kamini
ha
andhi
hon
gandi
ha
purani
hon
pagali
ha
purani
hon
ghinoni
ha
purani
hon
kamini
ha
purani
hon
gandi
ha
stree
hon
pagali
ha
stree
hon
ghinoni
ha
stree
hon
kamini
ha
stree
hon
gandi
ha
bahot
purani
hon
pagali
ha
bahot
purani
hon
ghinoni
ha
bahot
purani
hon
kamini
ha
bahot
purani
hon
gandi
ha
purana
hona
pagali
ha
purana
hona
ghinoni
ha
purana
hona
kamini
ha
purana
hona
gandi
ha
kala
hona
pagali
ha
kala
hona
ghinoni
ha
kala
hona
kamini
ha
kala
hona
gandi
ha
andha
hona
pagali
ha
andha
hona
ghinoni
ha
andha
hona
kamini
ha
andha
hona
gandi
ha
purush
hona
pagali
ha
purush
hona
ghinoni
ha
purush
hona
kamini
ha
purush
hona
gandi
ha
bahot
purana
hona
pagali
ha
bahot
purana
hona
ghinoni
ha
bahot
purana
hona
kamini
ha
bahot
purana
hona
gandi
ha
kali
hona
pagali
ha
kali
hona
ghinoni
ha
kali
hona
kamini
ha
kali
hona
gandi
ha
andhi
hona
pagali
ha
andhi
hona
ghinoni
ha
andhi
hona
kamini
ha
andhi
hona
gandi
ha
purani
hona
pagali
ha
purani
hona
ghinoni
ha
purani
hona
kamini
ha
purani
hona
gandi
ha
stree
hona
pagali
ha
stree
hona
ghinoni
ha
stree
hona
kamini
ha
stree
hona
gandi
ha
bahot
purani
hona
pagali
ha
bahot
purani
hona
ghinoni
ha
bahot
purani
hona
kamini
ha
bahot
purani
hona
gandi
ha
purana
hona
pagali
hai
purana
hona
ghinoni
hai
purana
hona
kamini
hai
purana
hona
gandi
hai
kala
hona
pagali
hai
kala
hona
ghinoni
hai
kala
hona
kamini
hai
kala
hona
gandi
hai
andha
hona
pagali
hai
andha
hona
ghinoni
hai
andha
hona
kamini
hai
andha
hona
gandi
hai
purush
hona
pagali
hai
purush
hona
ghinoni
hai
purush
hona
kamini
hai
purush
hona
gandi
hai
bahot
purana
hona
pagali
hai
bahot
purana
hona
ghinoni
hai
bahot
purana
hona
kamini
hai
bahot
purana
hona
gandi
hai
kali
hona
pagali
hai
kali
hona
ghinoni
hai
kali
hona
kamini
hai
kali
hona
gandi
hai
andhi
hona
pagali
hai
andhi
hona
ghinoni
hai
andhi
hona
kamini
hai
andhi
hona
gandi
hai
purani
hona
pagali
hai
purani
hona
ghinoni
hai
purani
hona
kamini
hai
purani
hona
gandi
hai
stree
hona
pagali
hai
stree
hona
ghinoni
hai
stree
hona
kamini
hai
stree
hona
gandi
hai
bahot
purani
hona
pagali
hai
bahot
purani
hona
ghinoni
hai
bahot
purani
hona
kamini
hai
bahot
purani
hona
gandi
hai
purana
hona
pagali
he
purana
hona
ghinoni
he
purana
hona
kamini
he
purana
hona
gandi
he
kala
hona
pagali
he
kala
hona
ghinoni
he
kala
hona
kamini
he
kala
hona
gandi
he
andha
hona
pagali
he
andha
hona
ghinoni
he
andha
hona
kamini
he
andha
hona
gandi
he
purush
hona
pagali
he
purush
hona
ghinoni
he
purush
hona
kamini
he
purush
hona
gandi
he
bahot
purana
hona
pagali
he
bahot
purana
hona
ghinoni
he
bahot
purana
hona
kamini
he
bahot
purana
hona
gandi
he
kali
hona
pagali
he
kali
hona
ghinoni
he
kali
hona
kamini
he
kali
hona
gandi
he
andhi
hona
pagali
he
andhi
hona
ghinoni
he
andhi
hona
kamini
he
andhi
hona
gandi
he
purani
hona
pagali
he
purani
hona
ghinoni
he
purani
hona
kamini
he
purani
hona
gandi
he
stree
hona
pagali
he
stree
hona
ghinoni
he
stree
hona
kamini
he
stree
hona
gandi
he
bahot
purani
hona
pagali
he
bahot
purani
hona
ghinoni
he
bahot
purani
hona
kamini
he
bahot
purani
hona
gandi
he
purana
hona
pagali
hey
purana
hona
ghinoni
hey
purana
hona
kamini
hey
purana
hona
gandi
hey
kala
hona
pagali
hey
kala
hona
ghinoni
hey
kala
hona
kamini
hey
kala
hona
gandi
hey
andha
hona
pagali
hey
andha
hona
ghinoni
hey
andha
hona
kamini
hey
andha
hona
gandi
hey
purush
hona
pagali
hey
purush
hona
ghinoni
hey
purush
hona
kamini
hey
purush
hona
gandi
hey
bahot
purana
hona
pagali
hey
bahot
purana
hona
ghinoni
hey
bahot
purana
hona
kamini
hey
bahot
purana
hona
gandi
hey
kali
hona
pagali
hey
kali
hona
ghinoni
hey
kali
hona
kamini
hey
kali
hona
gandi
hey
andhi
hona
pagali
hey
andhi
hona
ghinoni
hey
andhi
hona
kamini
hey
andhi
hona
gandi
hey
purani
hona
pagali
hey
purani
hona
ghinoni
hey
purani
hona
kamini
hey
purani
hona
gandi
hey
stree
hona
pagali
hey
stree
hona
ghinoni
hey
stree
hona
kamini
hey
stree
hona
gandi
hey
bahot
purani
hona
pagali
hey
bahot
purani
hona
ghinoni
hey
bahot
purani
hona
kamini
hey
bahot
purani
hona
gandi
hey
purana
honaa
pagali
he
purana
honaa
ghinoni
he
purana
honaa
kamini
he
purana
honaa
gandi
he
kala
honaa
pagali
he
kala
honaa
ghinoni
he
kala
honaa
kamini
he
kala
honaa
gandi
he
andha
honaa
pagali
he
andha
honaa
ghinoni
he
andha
honaa
kamini
he
andha
honaa
gandi
he
purush
honaa
pagali
he
purush
honaa
ghinoni
he
purush
honaa
kamini
he
purush
honaa
gandi
he
bahot
purana
honaa
pagali
he
bahot
purana
honaa
ghinoni
he
bahot
purana
honaa
kamini
he
bahot
purana
honaa
gandi
he
kali
honaa
pagali
he
kali
honaa
ghinoni
he
kali
honaa
kamini
he
kali
honaa
gandi
he
andhi
honaa
pagali
he
andhi
honaa
ghinoni
he
andhi
honaa
kamini
he
andhi
honaa
gandi
he
purani
honaa
pagali
he
purani
honaa
ghinoni
he
purani
honaa
kamini
he
purani
honaa
gandi
he
stree
honaa
pagali
he
stree
honaa
ghinoni
he
stree
honaa
kamini
he
stree
honaa
gandi
he
bahot
purani
honaa
pagali
he
bahot
purani
honaa
ghinoni
he
bahot
purani
honaa
kamini
he
bahot
purani
honaa
gandi
he
aap
anokhi
purana
vyakti
hai
aap
anokhi
kala
vyakti
hai
aap
anokhi
andha
vyakti
hai
aap
anokhi
purush
vyakti
hai
aap
anokhi
bahot
purana
vyakti
hai
aap
acchi
purana
vyakti
hai
aap
acchi
kala
vyakti
hai
aap
acchi
andha
vyakti
hai
aap
acchi
purush
vyakti
hai
aap
acchi
bahot
purana
vyakti
hai
aap
pyari
purana
vyakti
hai
aap
pyari
kala
vyakti
hai
aap
pyari
andha
vyakti
hai
aap
pyari
purush
vyakti
hai
aap
pyari
bahot
purana
vyakti
hai
aap
anokhi
kali
vyakti
hai
aap
anokhi
andhi
vyakti
hai
aap
anokhi
purani
vyakti
hai
aap
anokhi
stree
vyakti
hai
aap
anokhi
bahot
purani
vyakti
hai
aap
acchi
kali
vyakti
hai
aap
acchi
andhi
vyakti
hai
aap
acchi
purani
vyakti
hai
aap
acchi
stree
vyakti
hai
aap
acchi
bahot
purani
vyakti
hai
aap
pyari
kali
vyakti
hai
aap
pyari
andhi
vyakti
hai
aap
pyari
purani
vyakti
hai
aap
pyari
stree
vyakti
hai
aap
pyari
bahot
purani
vyakti
hai
aap
anokhi
purana
vyakti
hain
aap
anokhi
kala
vyakti
hain
aap
anokhi
andha
vyakti
hain
aap
anokhi
purush
vyakti
hain
aap
anokhi
bahot
purana
vyakti
hain
aap
acchi
purana
vyakti
hain
aap
acchi
kala
vyakti
hain
aap
acchi
andha
vyakti
hain
aap
acchi
purush
vyakti
hain
aap
acchi
bahot
purana
vyakti
hain
aap
pyari
purana
vyakti
hain
aap
pyari
kala
vyakti
hain
aap
pyari
andha
vyakti
hain
aap
pyari
purush
vyakti
hain
aap
pyari
bahot
purana
vyakti
hain
aap
anokhi
kali
vyakti
hain
aap
anokhi
andhi
vyakti
hain
aap
anokhi
purani
vyakti
hain
aap
anokhi
stree
vyakti
hain
aap
anokhi
bahot
purani
vyakti
hain
aap
acchi
kali
vyakti
hain
aap
acchi
andhi
vyakti
hain
aap
acchi
purani
vyakti
hain
aap
acchi
stree
vyakti
hain
aap
acchi
bahot
purani
vyakti
hain
aap
pyari
kali
vyakti
hain
aap
pyari
andhi
vyakti
hain
aap
pyari
purani
vyakti
hain
aap
pyari
stree
vyakti
hain
aap
pyari
bahot
purani
vyakti
hain
aap
anokhi
purana
vyakti
han
aap
anokhi
kala
vyakti
han
aap
anokhi
andha
vyakti
han
aap
anokhi
purush
vyakti
han
aap
anokhi
bahot
purana
vyakti
han
aap
acchi
purana
vyakti
han
aap
acchi
kala
vyakti
han
aap
acchi
andha
vyakti
han
aap
acchi
purush
vyakti
han
aap
acchi
bahot
purana
vyakti
han
aap
pyari
purana
vyakti
han
aap
pyari
kala
vyakti
han
aap
pyari
andha
vyakti
han
aap
pyari
purush
vyakti
han
aap
pyari
bahot
purana
vyakti
han
aap
anokhi
kali
vyakti
han
aap
anokhi
andhi
vyakti
han
aap
anokhi
purani
vyakti
han
aap
anokhi
stree
vyakti
han
aap
anokhi
bahot
purani
vyakti
han
aap
acchi
kali
vyakti
han
aap
acchi
andhi
vyakti
han
aap
acchi
purani
vyakti
han
aap
acchi
stree
vyakti
han
aap
acchi
bahot
purani
vyakti
han
aap
pyari
kali
vyakti
han
aap
pyari
andhi
vyakti
han
aap
pyari
purani
vyakti
han
aap
pyari
stree
vyakti
han
aap
pyari
bahot
purani
vyakti
han
aap
anokhi
purana
vyakti
hen
aap
anokhi
kala
vyakti
hen
aap
anokhi
andha
vyakti
hen
aap
anokhi
purush
vyakti
hen
aap
anokhi
bahot
purana
vyakti
hen
aap
acchi
purana
vyakti
hen
aap
acchi
kala
vyakti
hen
aap
acchi
andha
vyakti
hen
aap
acchi
purush
vyakti
hen
aap
acchi
bahot
purana
vyakti
hen
aap
pyari
purana
vyakti
hen
aap
pyari
kala
vyakti
hen
aap
pyari
andha
vyakti
hen
aap
pyari
purush
vyakti
hen
aap
pyari
bahot
purana
vyakti
hen
aap
anokhi
kali
vyakti
hen
aap
anokhi
andhi
vyakti
hen
aap
anokhi
purani
vyakti
hen
aap
anokhi
stree
vyakti
hen
aap
anokhi
bahot
purani
vyakti
hen
aap
acchi
kali
vyakti
hen
aap
acchi
andhi
vyakti
hen
aap
acchi
purani
vyakti
hen
aap
acchi
stree
vyakti
hen
aap
acchi
bahot
purani
vyakti
hen
aap
pyari
kali
vyakti
hen
aap
pyari
andhi
vyakti
hen
aap
pyari
purani
vyakti
hen
aap
pyari
stree
vyakti
hen
aap
pyari
bahot
purani
vyakti
hen
aap
anokhi
purana
vykti
ha
aap
anokhi
kala
vykti
ha
aap
anokhi
andha
vykti
ha
aap
anokhi
purush
vykti
ha
aap
anokhi
bahot
purana
vykti
ha
aap
acchi
purana
vykti
ha
aap
acchi
kala
vykti
ha
aap
acchi
andha
vykti
ha
aap
acchi
purush
vykti
ha
aap
acchi
bahot
purana
vykti
ha
aap
pyari
purana
vykti
ha
aap
pyari
kala
vykti
ha
aap
pyari
andha
vykti
ha
aap
pyari
purush
vykti
ha
aap
pyari
bahot
purana
vykti
ha
aap
anokhi
kali
vykti
ha
aap
anokhi
andhi
vykti
ha
aap
anokhi
purani
vykti
ha
aap
anokhi
stree
vykti
ha
aap
anokhi
bahot
purani
vykti
ha
aap
acchi
kali
vykti
ha
aap
acchi
andhi
vykti
ha
aap
acchi
purani
vykti
ha
aap
acchi
stree
vykti
ha
aap
acchi
bahot
purani
vykti
ha
aap
pyari
kali
vykti
ha
aap
pyari
andhi
vykti
ha
aap
pyari
purani
vykti
ha
aap
pyari
stree
vykti
ha
aap
pyari
bahot
purani
vykti
ha
aap
anokhi
purana
vykti
hain
aap
anokhi
kala
vykti
hain
aap
anokhi
andha
vykti
hain
aap
anokhi
purush
vykti
hain
aap
anokhi
bahot
purana
vykti
hain
aap
acchi
purana
vykti
hain
aap
acchi
kala
vykti
hain
aap
acchi
andha
vykti
hain
aap
acchi
purush
vykti
hain
aap
acchi
bahot
purana
vykti
hain
aap
pyari
purana
vykti
hain
aap
pyari
kala
vykti
hain
aap
pyari
andha
vykti
hain
aap
pyari
purush
vykti
hain
aap
pyari
bahot
purana
vykti
hain
aap
anokhi
kali
vykti
hain
aap
anokhi
andhi
vykti
hain
aap
anokhi
purani
vykti
hain
aap
anokhi
stree
vykti
hain
aap
anokhi
bahot
purani
vykti
hain
aap
acchi
kali
vykti
hain
aap
acchi
andhi
vykti
hain
aap
acchi
purani
vykti
hain
aap
acchi
stree
vykti
hain
aap
acchi
bahot
purani
vykti
hain
aap
pyari
kali
vykti
hain
aap
pyari
andhi
vykti
hain
aap
pyari
purani
vykti
hain
aap
pyari
stree
vykti
hain
aap
pyari
bahot
purani
vykti
hain
aap
anokhi
purana
vykti
hann
aap
anokhi
kala
vykti
hann
aap
anokhi
andha
vykti
hann
aap
anokhi
purush
vykti
hann
aap
anokhi
bahot
purana
vykti
hann
aap
acchi
purana
vykti
hann
aap
acchi
kala
vykti
hann
aap
acchi
andha
vykti
hann
aap
acchi
purush
vykti
hann
aap
acchi
bahot
purana
vykti
hann
aap
pyari
purana
vykti
hann
aap
pyari
kala
vykti
hann
aap
pyari
andha
vykti
hann
aap
pyari
purush
vykti
hann
aap
pyari
bahot
purana
vykti
hann
aap
anokhi
kali
vykti
hann
aap
anokhi
andhi
vykti
hann
aap
anokhi
purani
vykti
hann
aap
anokhi
stree
vykti
hann
aap
anokhi
bahot
purani
vykti
hann
aap
acchi
kali
vykti
hann
aap
acchi
andhi
vykti
hann
aap
acchi
purani
vykti
hann
aap
acchi
stree
vykti
hann
aap
acchi
bahot
purani
vykti
hann
aap
pyari
kali
vykti
hann
aap
pyari
andhi
vykti
hann
aap
pyari
purani
vykti
hann
aap
pyari
stree
vykti
hann
aap
pyari
bahot
purani
vykti
hann
aaph
anokhi
purana
vaykti
hen
aaph
anokhi
kala
vaykti
hen
aaph
anokhi
andha
vaykti
hen
aaph
anokhi
purush
vaykti
hen
aaph
anokhi
bahot
purana
vaykti
hen
aaph
acchi
purana
vaykti
hen
aaph
acchi
kala
vaykti
hen
aaph
acchi
andha
vaykti
hen
aaph
acchi
purush
vaykti
hen
aaph
acchi
bahot
purana
vaykti
hen
aaph
pyari
purana
vaykti
hen
aaph
pyari
kala
vaykti
hen
aaph
pyari
andha
vaykti
hen
aaph
pyari
purush
vaykti
hen
aaph
pyari
bahot
purana
vaykti
hen
aaph
anokhi
kali
vaykti
hen
aaph
anokhi
andhi
vaykti
hen
aaph
anokhi
purani
vaykti
hen
aaph
anokhi
stree
vaykti
hen
aaph
anokhi
bahot
purani
vaykti
hen
aaph
acchi
kali
vaykti
hen
aaph
acchi
andhi
vaykti
hen
aaph
acchi
purani
vaykti
hen
aaph
acchi
stree
vaykti
hen
aaph
acchi
bahot
purani
vaykti
hen
aaph
pyari
kali
vaykti
hen
aaph
pyari
andhi
vaykti
hen
aaph
pyari
purani
vaykti
hen
aaph
pyari
stree
vaykti
hen
aaph
pyari
bahot
purani
vaykti
hen
ap
anokhi
purana
vyakti
ha
ap
anokhi
kala
vyakti
ha
ap
anokhi
andha
vyakti
ha
ap
anokhi
purush
vyakti
ha
ap
anokhi
bahot
purana
vyakti
ha
ap
acchi
purana
vyakti
ha
ap
acchi
kala
vyakti
ha
ap
acchi
andha
vyakti
ha
ap
acchi
purush
vyakti
ha
ap
acchi
bahot
purana
vyakti
ha
ap
pyari
purana
vyakti
ha
ap
pyari
kala
vyakti
ha
ap
pyari
andha
vyakti
ha
ap
pyari
purush
vyakti
ha
ap
pyari
bahot
purana
vyakti
ha
ap
anokhi
kali
vyakti
ha
ap
anokhi
andhi
vyakti
ha
ap
anokhi
purani
vyakti
ha
ap
anokhi
stree
vyakti
ha
ap
anokhi
bahot
purani
vyakti
ha
ap
acchi
kali
vyakti
ha
ap
acchi
andhi
vyakti
ha
ap
acchi
purani
vyakti
ha
ap
acchi
stree
vyakti
ha
ap
acchi
bahot
purani
vyakti
ha
ap
pyari
kali
vyakti
ha
ap
pyari
andhi
vyakti
ha
ap
pyari
purani
vyakti
ha
ap
pyari
stree
vyakti
ha
ap
pyari
bahot
purani
vyakti
ha
op
anokhi
purana
vyakt
hai
op
anokhi
kala
vyakt
hai
op
anokhi
andha
vyakt
hai
op
anokhi
purush
vyakt
hai
op
anokhi
bahot
purana
vyakt
hai
op
acchi
purana
vyakt
hai
op
acchi
kala
vyakt
hai
op
acchi
andha
vyakt
hai
op
acchi
purush
vyakt
hai
op
acchi
bahot
purana
vyakt
hai
op
pyari
purana
vyakt
hai
op
pyari
kala
vyakt
hai
op
pyari
andha
vyakt
hai
op
pyari
purush
vyakt
hai
op
pyari
bahot
purana
vyakt
hai
op
anokhi
kali
vyakt
hai
op
anokhi
andhi
vyakt
hai
op
anokhi
purani
vyakt
hai
op
anokhi
stree
vyakt
hai
op
anokhi
bahot
purani
vyakt
hai
op
acchi
kali
vyakt
hai
op
acchi
andhi
vyakt
hai
op
acchi
purani
vyakt
hai
op
acchi
stree
vyakt
hai
op
acchi
bahot
purani
vyakt
hai
op
pyari
kali
vyakt
hai
op
pyari
andhi
vyakt
hai
op
pyari
purani
vyakt
hai
op
pyari
stree
vyakt
hai
op
pyari
bahot
purani
vyakt
hai
aap
pagali
purana
vyakti
hai
aap
pagali
kala
vyakti
hai
aap
pagali
andha
vyakti
hai
aap
pagali
purush
vyakti
hai
aap
pagali
bahot
purana
vyakti
hai
aap
ghinoni
purana
vyakti
hai
aap
ghinoni
kala
vyakti
hai
aap
ghinoni
andha
vyakti
hai
aap
ghinoni
purush
vyakti
hai
aap
ghinoni
bahot
purana
vyakti
hai
aap
kamini
purana
vyakti
hai
aap
kamini
kala
vyakti
hai
aap
kamini
andha
vyakti
hai
aap
kamini
purush
vyakti
hai
aap
kamini
bahot
purana
vyakti
hai
aap
gandi
purana
vyakti
hai
aap
gandi
kala
vyakti
hai
aap
gandi
andha
vyakti
hai
aap
gandi
purush
vyakti
hai
aap
gandi
bahot
purana
vyakti
hai
aap
pagali
kali
vyakti
hai
aap
pagali
andhi
vyakti
hai
aap
pagali
purani
vyakti
hai
aap
pagali
stree
vyakti
hai
aap
pagali
bahot
purani
vyakti
hai
aap
ghinoni
kali
vyakti
hai
aap
ghinoni
andhi
vyakti
hai
aap
ghinoni
purani
vyakti
hai
aap
ghinoni
stree
vyakti
hai
aap
ghinoni
bahot
purani
vyakti
hai
aap
kamini
kali
vyakti
hai
aap
kamini
andhi
vyakti
hai
aap
kamini
purani
vyakti
hai
aap
kamini
stree
vyakti
hai
aap
kamini
bahot
purani
vyakti
hai
aap
gandi
kali
vyakti
hai
aap
gandi
andhi
vyakti
hai
aap
gandi
purani
vyakti
hai
aap
gandi
stree
vyakti
hai
aap
gandi
bahot
purani
vyakti
hai
aap
pagali
purana
vyakti
hain
aap
pagali
kala
vyakti
hain
aap
pagali
andha
vyakti
hain
aap
pagali
purush
vyakti
hain
aap
pagali
bahot
purana
vyakti
hain
aap
ghinoni
purana
vyakti
hain
aap
ghinoni
kala
vyakti
hain
aap
ghinoni
andha
vyakti
hain
aap
ghinoni
purush
vyakti
hain
aap
ghinoni
bahot
purana
vyakti
hain
aap
kamini
purana
vyakti
hain
aap
kamini
kala
vyakti
hain
aap
kamini
andha
vyakti
hain
aap
kamini
purush
vyakti
hain
aap
kamini
bahot
purana
vyakti
hain
aap
gandi
purana
vyakti
hain
aap
gandi
kala
vyakti
hain
aap
gandi
andha
vyakti
hain
aap
gandi
purush
vyakti
hain
aap
gandi
bahot
purana
vyakti
hain
aap
pagali
kali
vyakti
hain
aap
pagali
andhi
vyakti
hain
aap
pagali
purani
vyakti
hain
aap
pagali
stree
vyakti
hain
aap
pagali
bahot
purani
vyakti
hain
aap
ghinoni
kali
vyakti
hain
aap
ghinoni
andhi
vyakti
hain
aap
ghinoni
purani
vyakti
hain
aap
ghinoni
stree
vyakti
hain
aap
ghinoni
bahot
purani
vyakti
hain
aap
kamini
kali
vyakti
hain
aap
kamini
andhi
vyakti
hain
aap
kamini
purani
vyakti
hain
aap
kamini
stree
vyakti
hain
aap
kamini
bahot
purani
vyakti
hain
aap
gandi
kali
vyakti
hain
aap
gandi
andhi
vyakti
hain
aap
gandi
purani
vyakti
hain
aap
gandi
stree
vyakti
hain
aap
gandi
bahot
purani
vyakti
hain
aap
pagali
purana
vyakti
han
aap
pagali
kala
vyakti
han
aap
pagali
andha
vyakti
han
aap
pagali
purush
vyakti
han
aap
pagali
bahot
purana
vyakti
han
aap
ghinoni
purana
vyakti
han
aap
ghinoni
kala
vyakti
han
aap
ghinoni
andha
vyakti
han
aap
ghinoni
purush
vyakti
han
aap
ghinoni
bahot
purana
vyakti
han
aap
kamini
purana
vyakti
han
aap
kamini
kala
vyakti
han
aap
kamini
andha
vyakti
han
aap
kamini
purush
vyakti
han
aap
kamini
bahot
purana
vyakti
han
aap
gandi
purana
vyakti
han
aap
gandi
kala
vyakti
han
aap
gandi
andha
vyakti
han
aap
gandi
purush
vyakti
han
aap
gandi
bahot
purana
vyakti
han
aap
pagali
kali
vyakti
han
aap
pagali
andhi
vyakti
han
aap
pagali
purani
vyakti
han
aap
pagali
stree
vyakti
han
aap
pagali
bahot
purani
vyakti
han
aap
ghinoni
kali
vyakti
han
aap
ghinoni
andhi
vyakti
han
aap
ghinoni
purani
vyakti
han
aap
ghinoni
stree
vyakti
han
aap
ghinoni
bahot
purani
vyakti
han
aap
kamini
kali
vyakti
han
aap
kamini
andhi
vyakti
han
aap
kamini
purani
vyakti
han
aap
kamini
stree
vyakti
han
aap
kamini
bahot
purani
vyakti
han
aap
gandi
kali
vyakti
han
aap
gandi
andhi
vyakti
han
aap
gandi
purani
vyakti
han
aap
gandi
stree
vyakti
han
aap
gandi
bahot
purani
vyakti
han
aap
pagali
purana
vyakti
hen
aap
pagali
kala
vyakti
hen
aap
pagali
andha
vyakti
hen
aap
pagali
purush
vyakti
hen
aap
pagali
bahot
purana
vyakti
hen
aap
ghinoni
purana
vyakti
hen
aap
ghinoni
kala
vyakti
hen
aap
ghinoni
andha
vyakti
hen
aap
ghinoni
purush
vyakti
hen
aap
ghinoni
bahot
purana
vyakti
hen

In [ ]:
y=df['toxicity']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500)
X = cv.fit_transform(corpus).toarray()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
hatespeech_detect_model = MultinomialNB().fit(X_train, y_train)

In [ ]:
y_pred=hatespeech_detect_model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)
print(score)

1.0

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2646
           1       1.00      1.00      1.00      2836

    accuracy                           1.00      5482
   macro avg       1.00      1.00      1.00      5482
weighted avg       1.00      1.00      1.00      5482

In [ ]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)
y_pred=classifier.predict(X_test)
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2646
           1       1.00      1.00      1.00      2836

    accuracy                           1.00      5482
   macro avg       1.00      1.00      1.00      5482
weighted avg       1.00      1.00      1.00      5482